update

diff --git a/.github/workflows/checkout.yml b/.github/workflows/checkout.yml
--- a/.github/workflows/checkout.yml
+++ b/.github/workflows/checkout.yml
@@ -9,6 +9,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
 
+      - name: Check if AssetsRepo is set
+        run: |
+          if [ -z "${{ vars.AssetsRepo }}" ]; then
+            echo "Error: AssetsRepo is not set"
+            exit 1
+          fi
+
       - uses: actions/checkout@v4
         with:
           repository: ${{ vars.AssetsRepo }}
